### PR TITLE
doc: auto-generate documentation

### LINKED ISSUE #88: Forge section instructions update
[This line](https://github.com/maticnetwork/polygon-cli/blob/main/README.md?plain=1#L295) has a 404 (broken link)

This URL doesn't work anymore:
https://wiki.polygon.technology/docs/edge/get-started/set-up-ibft-locally

Instead this one could be a better option now:
https://wiki.polygon.technology/docs/supernets/operate/deploy/supernets-how-to-generate-genesis

But if the link is changed, the `abridged` instructions just below that  based on the IBFT consensus protocol should also be changed to the PolyBFT example on the official docs. Is this change ok or there is a more appropriate link?

Current `abridged` instructions are:
```
go install github.com/0xPolygon/polygon-edge@develop

polygon-edge secrets init --data-dir test-chain-1
# record the node id
NODE_ID=$(polygon-edge secrets output --node-id --data-dir test-chain-1)

# generate the genesis.json file
# note: you may have to add some fields to the alloc property there may be an insufficient funds error
polygon-edge genesis --ibft-validators-prefix-path test-chain- --bootnode /ip4/127.0.0.1/tcp/10001/p2p/$NODE_ID --block-gas-limit 6706541
```

### PR DESCRIPTION
**Pull request by leovct**
# Description

While working on #101, I noticed that we have lots of content duplicated across our go files and the `README`. Most of the time, the commands are both described in the `cobra.Commad` and in the `README`. Sometimes, the descriptions are a little different, the examples may vary, or sometimes, the documentation is simply missing.

We should advocate for software automation to handle the task of updating our docs instead of relying on manual efforts. This way, our doc will always be up-to-date and standardised. To achieve this, I suggest to leverage the features of `cobra` to auto-generate commands doc. This script will run in CI to check if the doc is properly updated given the latest changes. Anyone can run the script locally (just like a linter) to update the doc using `make gen-doc`.

```sh
$ make gen-doc
go run docutil/*.go
Documentation generated!
```

Most of the code for generating the documentation is located under `docutil`. The doc is found in the `doc` folder and the `README` makes a reference to `doc/polycli.md`, the entry point of the doc.

Cobra makes it very easy to generate documentation from commands but it hardcodes the way the Markdown is formatted (e.g. some headers and fields can't be modified). That's why I copy/pasted most of the code and modified it to better meet our needs.

It also resolves #88.

# Screenshots

Screenshot 2023-07-07 at 10 49 17

Screenshot 2023-07-07 at 10 51 49

## Jira / Linear Tickets

- [DVT-858]()

# Testing

- [x] Auto-generate `polycli` documentation
- [x] Add CI job to make sure the doc is always up-to-date

[DVT-858]: https://polygon.atlassian.net/browse/DVT-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by leovct** [comment]
Simple test: I updated the `abi` command but didn't update the docs. The job [failed](https://github.com/maticnetwork/polygon-cli/actions/runs/5484740190/jobs/9992684380?pr=103) as expected.

**Comment by praetoriansentry** [comment]
This is great. Three light recommendations / ideas:
1. I think an index of commands in the main readme that link to the individual docs would be nice. This gives a sense of the variety of commands right away and provides easy access without neeting to click to `docs` first
2.Some of the handy commands at the bottom of the README feel out of place now. I think you could drop that
3. I think some kind of visual on the README would be nice. You could include some gif or screenshot from polycli. I would probalby do `monitor` or something else interesting

**Comment by leovct** [comment]
> This is great. Three light recommendations / ideas:
> 
> 1. I think an index of commands in the main readme that link to the individual docs would be nice. This gives a sense of the variety of commands right away and provides easy access without neeting to click to `docs` first
> 2. Some of the handy commands at the bottom of the README feel out of place now. I think you could drop that
> 3. I think some kind of visual on the README would be nice. You could include some gif or screenshot from polycli. I would probalby do `monitor` or something else interesting

Thanks for the review, I updated the PR :)

**Review by praetoriansentry — APPROVED** [review]

**Comment by criadoperez** [comment]
Thanks @leovct!

**Pull request merged**
