### PR TITLE
error when batch limit error + add sub batch arg

### PR DESCRIPTION
**Pull request by gatsbyz**
log why batch call is failing so we are not lost
i made the retry + backoff a go routine… but this still prevents ctrl+c when it’s retrying :shrug:
force stop batch retry when the error is “batch limit”

### CODE REVIEW

**Comment by leovct** [comment]
Not sure about the rest of the changes in the PR but just these lines fixed the issue for me.

```go
// func (ms *monitorStatus) processBatchesConcurrently(ctx context.Context, rpc *ethrpc.Client, blms []ethrpc.BatchElem) error {
retryable := func() error {
	if err := rpc.BatchCallContext(ctx, subBatch); err != nil {
		log.Error().Err(err).Msg("Error when performing batch calls")
		return backoff.Permanent(err)
	}
	return nil
}
```

**Comment by gatsbyz** [comment]
@leovct the other changes are basically an attempt to make Ctrl+C work when BatchCall retry is happening, but it's not working as intended. `backoff.Permanent(err)` will force quit the retry, so if wrap the error with that in any failure, the retry will never happen I think?

**Review by leovct — APPROVED** [review]
lgtm

I hope nobody will return an error with `limit` other than batch limit errors lol!
Maybe add a note that this is a dirty hack ;)

**Comment by leovct** [comment]
Solc [0.8.24](https://github.com/ethereum/solidity/releases) just went out, that's why the CI breaks... I'll send a PR to make sure it doesn't break again!

**Pull request merged**
